### ISSUE TITLE
Panik when moving mouse into window while scrolling.

### ISSUE THREAD

**Issue by laundmo** [johanhelsing/bevy_pancam#12]
when moving the mouse from outside the window into it while at the same time scrolling, bevy_pancam will crash with:
```
thread 'Compute Task Pool (1)' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\laundmo\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_pancam-0.5.0\src\lib.rs:38:10
```

This is because a scroll event has been picked up before the mouse is inside the window, causing the unwrap to panik on the mouse position.

a fix could be a simple `if let Some(cursor) = window.cursor_position()` instead of unwrap.

**Comment by johanhelsing** [comment]
Right. Thanks for the report! I agree with the solution.

Do you want to make a PR, or should I?

**Comment by laundmo** [comment]
go ahead, faster if you do it, i would have to set up everything first and then youd have to merge it anyways
