### ISSUE TITLE
Ability to control whether camera is active

### ISSUE THREAD

**Issue by jakobhellermann** [johanhelsing/bevy_pancam#2]
It would be useful to be able to toggle whether or not received inputs should be accepted so that you can disable the camera.

This could be e.g. a `enabled` bool on the `PanCam` component (<https://docs.rs/bevy_fly_camera/latest/bevy_fly_camera/struct.FlyCamera.html#structfield.enabled>).

**Comment by johanhelsing** [comment]
Good idea :) Fixed!
