### ISSUE TITLE
Keyboard movement

### ISSUE THREAD

**Issue by Toniman575** [johanhelsing/bevy_pancam#52]
I would like to create a PR to add keyboard movement if that is desired?

**Comment by Indeximal** [comment]
I just tried using my existing keyboard movement system with this plugin and it works flawlessly. I guess this would be an argument against also including that in this plugin and instead create (or find) a separate plugin.

**Comment by johanhelsing** [comment]
If we add this feature, does it make more sense to have constant speed or acceleration-based movement (with max speed)?

**Comment by Toniman575** [comment]
I feel like constant speed should cover most use cases fairly well, but I could just add both in my PR?

**Comment by PerfectlyInternal** [comment]
Has there been any progress on this? I can start working if nobody's working on this. I was hoping to use this feature for a project of my own, so I'd like to have it implemented soon.
